version: "3.9"

services:

  nginx:
    image: lscr.io/linuxserver/nginx:latest
    container_name: dasherr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - ./www:/config/www
    ports:
      - "8200:80"
      - "8443:443"
    restart: unless-stopped

    
